// Generated by https://quicktype.io

export interface Academys {
  academys: Academy[];
}

export interface Academy {
  title: string;
  institucion: string;
  descripcion: string;
  duracion: string;
  fecha_desde_hasta: string;
  actual: boolean;
}
