// Generated by https://quicktype.io

export interface Certificates {
  certificates: Certificate[];
}

export interface Certificate {
  image: string;
  title: string;
  tags: string[];
  academy: string;
  range_fecha: string;
}
