// Generated by https://quicktype.io

export interface Certificates {
  certificados: Certificate[];
}

export interface Certificate {
  imagen: string;
  titulo: string;
  tags: string[];
  academia: string;
  rango_fecha: string;
  certificado: string;
  btn_load?: boolean;
  mensaje_btn?: string;
}

