// Generated by https://quicktype.io

export interface Estudios {
  current_page: number;
  data: Estudio[];
  first_page_url: string;
  from: number;
  last_page: number;
  last_page_url: string;
  links: Link[];
  next_page_url: string;
  path: string;
  per_page: number;
  prev_page_url: null;
  to: number;
  total: number;
}

export interface Estudio {
  id: number;
  title: string;
  institucion: string;
  descripcion: string;
  duracion: string;
  fecha_desde_hasta: string;
  actual: number;
}

export interface Link {
  url: null | string;
  label: string;
  active: boolean;
}
