// Generated by https://quicktype.io

export interface Testimonials {
  testimonials: Testimonial[];
}

export interface Testimonial {
  descripcion: string;
  cliente: string;
  titulo: string;
  imagen: string;
}
