// Generated by https://quicktype.io

export interface Testimonials {
  testimonios: Testimonial[];
}

export interface Testimonial {
  id: number;
  cliente: string;
  cargo: string;
  descripcion: string;
  imagen: string;
}
